language: node_js
node_js:
  - "8"
services:
  - docker

before_install:
  - npm install

script:
  - npm run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t tiancaixiaobaozi/vue-cli3-demo:latest .
  - docker push tiancaixiaobaozi/vue-cli3-demo:latest
